
export const Students =[
    {
        id:1,
        name:"Mike",
        surname:"John",
        type:"Programmer",
    },
    {
        id:2,
        name:"Jone",
        surname:"Cormier",
        type:"Designer",
    },
    {
        id:3,
        name:"Harry",
        surname:"Smith",
        type:"Manager",
    },
    {
        id:4,
        name:"George",
        surname:"Ivanov",
        type:"Driver",
    },
    {
        id:5,
        name:"Mary",
        surname:"Yalle",
        type:"Chief",
    },
    {
        id:6,
        name:"Taylor",
        surname:"Kessler",
        type:"Developer",
    },
    {
        id:7,
        name:"Danny",
        surname:"Hoyer",
        type:"Speaker",
    },
    {
        id:8,
        name:"Ivan",
        surname:"Isacov",
        type:"Enterpreneaur",
    },
    {
        id:9,
        name:"Sasha",
        surname:"Kim",
        type:"Merketer",
    },
    {
        id:10,
        name:"Emmy",
        surname:"Randy",
        type:"Musician",
    }

]